---
version: "2.0"
services:
  translate-en-af:
    image: chadbrouze1/translation-service-app:0.1.2
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - AZURE_TRANSLATE_API_KEY=
      - AZURE_TRANSLATE_REGION=
      - POETRY_VIRTUALENVS_CREATE=false
      - FROM_LANGUAGE=en
      - TO_LANGUAGES=af
      - CLOSED_SOURCE_API=azure
      - OPEN_SOURCE_API=opus
      - ROUTER=advanced
      - BATCH_SIZE=16
      - LLM=ollama
      - CONDITIONS=code,min_chars
      - MIN_CHAR_LENGTH=
profiles:
  compute:
    translate-en-af:
      resources:
        cpu:
          units: 8
        memory:
          size: 8GB
        storage:
          - size: 8GB
  placement:
    dcloud:
      pricing:
        translate-en-af:
          denom: uakt
          amount: 1000
deployment:
  translate-en-af:
    dcloud:
      profile: translate-en-af
      count: 1